Wales
tmieslinger/how_to_eurec4a pull request #22
Opened 2021-02-17 10:52 UTC by tmieslinger

the notebook shows cloud parameters from the WALES Lidar, such as cloud flag, cloud optical thickness and cloud or boundary layer top height.

2021-02-17 12:44 UTC, d70-t requested changes
The markdown file is not yet formatted correctly to be rendered properly. Otherwise, it's just minor things, but as it did not yet render the outputs of the code cells, I didn't check the actual code very thoroughly.

2021-02-17 12:44 UTC, d70-t commented on how_to_eurec4a/wales.md
> +      format_name: markdown
The file is formatted in plain `markdown` in stead of [`myst`](https://jupyterbook.org/content/myst.html). It is required to format it in `myst` for the code cells to be executed.

2021-02-17 12:44 UTC, d70-t commented on how_to_eurec4a/wales.md
> +The system also contains additional aerosol channels at 532 nm and 1064 nm with depolarization.  WALES uses a high-spectral resolution technique, which distinguishes molecular from particle backscatt
This sounds as if direct extinction measurements are the only reason for building a HSRL lidar. I'd think that there are a few more reasons to do so :-)
```suggestion
The system also contains additional aerosol channels at 532 nm and 1064 nm with depolarization.  WALES uses a high-spectral resolution technique, which distinguishes molecular from particle backscatter. 
```

2021-02-17 12:44 UTC, d70-t commented on how_to_eurec4a/wales.md
> +```
Probably we should think more about how to factor this code out into a separate file as this kind of code became quite repetitive 😬

2021-02-17 12:44 UTC, d70-t commented on how_to_eurec4a/wales.md
> +\end{equation}
This does not render as an equation in the book. Probably this will do, but I didn't check:
```suggestion
$$
OT = -1/2 * ln(S(r)/S(0))
$$
```

2021-02-17 13:07 UTC, tmieslinger commented on how_to_eurec4a/wales.md
> +```
I agree :-) maybe we can work on the before creating the final versions of all notebooks

2021-02-17 13:07 UTC, tmieslinger commented on how_to_eurec4a/wales.md
> +The system also contains additional aerosol channels at 532 nm and 1064 nm with depolarization.  WALES uses a high-spectral resolution technique, which distinguishes molecular from particle backscatt
ok

2021-02-17 13:08 UTC, tmieslinger commented on how_to_eurec4a/wales.md
> +      format_name: markdown
sorry, wrong format 🙈

2021-02-17 13:08 UTC, tmieslinger commented on how_to_eurec4a/wales.md
> +\end{equation}
changed it

2021-02-17 17:24 UTC, d70-t reviewed
I like the plots a lot :tada:.
I've written down a few minor things which hopefully make the code a little bit more concise, which might help the readers to focus on the important parts. One issue might be hidden in the calculation of the time-averaged cloud fractions, which is inconsistent with the cloud fraction definition as used before.

2021-02-17 17:24 UTC, d70-t commented on how_to_eurec4a/wales.md
> +mask_cloud = np.array(ds_cloud_ll1.cloud_flag, dtype=bool)
This would be shorter and actually more precise. If I understand `mask_cloud` correctly, it should be true for everything which has been detected as a cloud. And as stated above `1` means cloudy. The current statement technically is more like `(ds_cloud_ll1.cloud_flag < 0) | (ds_cloud_ll1.cloud_flag > 0)`, probably with even more subtle edge cases.
```suggestion
mask_cloud = ds_cloud_ll1.cloud_flag==1
```

2021-02-17 17:24 UTC, d70-t commented on how_to_eurec4a/wales.md
> +                          ).mean()
Note that this does not necessarily provide the same results as `np.sum(ds_cloud.cloud_flag.values==1) / ds_cloud.cloud_flag.size`. In `xarray`, `mean()` is like `nanmean` and thus will skip all `nan` values present in `ds_cloud.cloud_flag` (i.e. will count `nan` values neither als cloudy nor as cloud free). On the contrary, `ds_cloud.cloud_flag.values==1` re-interprets all `nan` values as non-cloudy and `sum/size` or `mean` will count all original `nan` values as non-cloudy areas.

2021-02-17 17:24 UTC, d70-t commented on how_to_eurec4a/wales.md
> +    fraction_from_flag(ds_cloud.cloud_flag, t).plot(lw=ind + 1, label=f"{t} min")
This could also be done using xarray's resample functionality:
```suggestion
    ds_cloud.cloud_flag.resample(time=f"{t}min").mean().plot(lw=ind + 1, label=f"{t} min")
```
or
```suggestion
    (ds_cloud.cloud_flag==1).resample(time=f"{t}min").mean().plot(lw=ind + 1, label=f"{t} min")
```

2021-02-22 22:52 UTC, tmieslinger commented
Thanks @d70-t for the detailed review!
Due to a new file version of the WALES cloud parameter file including changes in the variables, I don't answer to your points above, but rather summarize the changes here:
* the unused flight segment is removed
* the variable `cloud_flag` was redesigned to `cloud_mask` with 4 flag values. Selecting certain flag values or times of a specific flag therefore changed at several points.
* for the cloud fraction part at the end I incorporated your suggestion. xarray.resample is great :)

2021-02-23 10:47 UTC, d70-t approved these changes
Thanks for updating it to the current version of the dataset. Looks good for now :tada:

2021-02-23 10:52 UTC, merged